### ISSUE TITLE
Create restriction for each paramater in the parameter class

### ISSUE THREAD

**Issue by Darpos** [tjex/decide-g26#63]

**Comment by a-kbd** [comment]
@Darpos @andersblomqvist tiny problem, how to put conditions on public static variables? 

I think we'd have to either instantiate them all in a constructor with conditions (will be a major PITA to write tests in the future) 

Alternatively, and maybe a bit better I find, is to just use setter functions that check conditions when setting the variables. However, there need to be checks that other variables that are part of the variable's condition are also set which could get messy quick. Also it would break many of the tests that use the `Parameters.xxx = value` syntax at the moment

**Comment by a-kbd** [comment]
won't fix, we came to the conclusion that this is not justified for the scope of the project
