### ISSUE TITLE
Many of the tests are not running for me

### ISSUE THREAD

**Issue by a-kbd** [tjex/decide-g26#70]
![image](https://user-images.githubusercontent.com/63161225/215287414-6b72f641-783c-4a77-8dac-ca782b2cfcda.png)

See picture, many of the tests don't run for me (gray dot). Like they're not failing either, they just don't run and it makes you believe that they are passing. I have no idea why this is, there are no build errors or anything similar

**Comment by andersblomqvist** [comment]
This is weird. When I ran all tests, everyone completed except `checkIfValidGivesTrueLic11` and `checkIfInvalidGivesFalseLic11`. However, when I closed the editor and ran everything again, then all LIC tests were grey.

This might be an issue with the testing env and not the actual tests.

**Comment by Darpos** [comment]
I have the same issues as above figure. Had it ever since pull with test for lic 9 I believe.

**Comment by Darpos** [comment]
![image](https://user-images.githubusercontent.com/34799012/215290242-4ad0a990-d6e9-48fe-be42-ef984026ae7e.png)
Maybe this will help?
